// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdpnilupxOofHhyA9-IUcWd3pbsJZGbrM',
    appId: '1:992288289317:web:431e7726caf00e2f6745cc',
    messagingSenderId: '992288289317',
    projectId: 'gpstag-3cce5',
    authDomain: 'gpstag-3cce5.firebaseapp.com',
    storageBucket: 'gpstag-3cce5.firebasestorage.app',
    measurementId: 'G-GFKKNVXTG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRuTq2MvHMCv3cZRK-jw_NBeWFyrls8Xc',
    appId: '1:992288289317:android:d501cf05032423e16745cc',
    messagingSenderId: '992288289317',
    projectId: 'gpstag-3cce5',
    storageBucket: 'gpstag-3cce5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB-i_aJLoSwFQYTK-5Czfn6Te2Fi3ndIA',
    appId: '1:992288289317:ios:72c011498077ef256745cc',
    messagingSenderId: '992288289317',
    projectId: 'gpstag-3cce5',
    storageBucket: 'gpstag-3cce5.firebasestorage.app',
    iosBundleId: 'com.example.busTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB-i_aJLoSwFQYTK-5Czfn6Te2Fi3ndIA',
    appId: '1:992288289317:ios:72c011498077ef256745cc',
    messagingSenderId: '992288289317',
    projectId: 'gpstag-3cce5',
    storageBucket: 'gpstag-3cce5.firebasestorage.app',
    iosBundleId: 'com.example.busTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdpnilupxOofHhyA9-IUcWd3pbsJZGbrM',
    appId: '1:992288289317:web:9bf5941fb98c0d226745cc',
    messagingSenderId: '992288289317',
    projectId: 'gpstag-3cce5',
    authDomain: 'gpstag-3cce5.firebaseapp.com',
    storageBucket: 'gpstag-3cce5.firebasestorage.app',
    measurementId: 'G-C93PXV0DWC',
  );
}
